/* DO NOT EDIT THIS FILE - it is machine generated */

#include "../../../../../../../AppData/Local/Android/Sdk/ndk-bundle/sysroot/usr/include/jni.h"
/* Header for class com_example_ygyg331_jnitest2_jniClass */

#ifndef _Included_com_example_ygyg331_jnitest2_jniClass
#define _Included_com_example_ygyg331_jnitest2_jniClass
#ifdef __c
extern "C" {
#endif
/*
 * Class:     com_example_ygyg331_jnitest2_jniClass
 * Method:    jniM
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_ygyg331_jnitest2_jniClass_jniM
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ygyg331_jnitest2_jniClass
 * Method:    getNumString
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_ygyg331_jnitest2_jniClass_getNumString
  (JNIEnv *, jobject, jstring, jint);

#ifdef __c
}
#endif
#endif
